export const PROGRESS_UPLOAD = 'PROGRESS_UPLOAD';
export const PROGRESS_PROCESS = 'PROGRESS_PROCESS';
export const PROGRESS_EXAMPLES = 'PROGRESS_EXAMPLES';
export const PROGRESS_STOPPED = 'PROGRESS_STOPPED';

export const UPDATE_FILES = 'UPDATE_FILES';
